version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - db
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - my_network
    depends_on:
      - db
    volumes:
      - ./backend:/app
    
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      # - db:/var/lib/postgresql/data
      - ./backend/sql/:/docker-entrypoint-initdb.d/
      # - $HOME/doc÷ker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db: 
    driver: local

networks:
  my_network:
      driver: bridge